### ISSUE TITLE
Error in as.Date.default(sensing_datetime) using Google Cloud SDK

### ISSUE THREAD

**Issue by sermomon** [ranghetti/sen2r#418]
I am trying to download S2 giving priority to Google Cloud server. I set up the Google Cloud SDK and it seems like everything is ready to go. I am using `"gcloud"` trying to complete my time series which is incomplete due to error #406 . I am not following the same approach as in your [documentation](https://luigi.ranghetti.info/post/safe-gcloud/), as I need to do some processing steps after download. So I am using `senr2()` function as follows:

```
suppressPackageStartupMessages({
  library(sen2r)
  library(getPass)
  library(raster)
})
```

```
# sen2r version >= 1.5.0:
packageVersion("sen2r")
```
[1] ‘1.5.0.9000’

```
# config and check GoogleCloud SDK
gsutil_dir <- "C:/Users/sergi/AppData/Local/Google/Cloud SDK"
check_gcloud(
    gsutil_dir,
    force = FALSE,
    full_scan = FALSE,
    abort = TRUE,
    check_creds = FALSE)
is_gcloud_configured()
check_gcloud_connection()
```
[1] TRUE
[1] TRUE
```
# login on Copernicus Open Access Hub
write_scihub_login(username= "sermomon", password= getPass::getPass())
```

```
# SEARCH CRITERIA #
###########################################################
# adquisition date
time_window <- as.Date(c("2019-06-01", "2019-06-30"))
# tile code
tile <- "30SYJ"
# max % of clouds
max_cloud <- 80
# product level
product_level <- "L2A"
# s2 orbit
id_orbit <- c("051")
# vegetation index
list_index <- c("NDVI", "CSI", "EVI", "GNDVI", "MCARI", "MCARI2", "MSI", "MTVI2", "NDWI", "NDVI2", "OSAVI", "SAVI", "BNDVI")
###########################################################
```

```
# define output directory
out <- paste0(output_directory, "/from_", time_window[1], "_to_", time_window[2], "_", toupper(months(time_window)[1]))
```
```
# sen2r
output_directory <- sen2r(
  gui = FALSE,
  s2tiles_selected = tile,
  timewindow = time_window,
  max_cloud_safe = max_cloud,
  s2orbits_selected = id_orbit,
  online = TRUE, order_lta = TRUE,
  server = c("gcloud", "scihub"),
  step_atmcorr = "auto",
  list_prods = c("BOA","SCL"), list_indices = list_index, list_rgb = c("RGB432B"),
  mask_type = "cloud_and_shadow", max_mask = 100,
  extent_name = "sen2r",
  path_l1c = out, path_l2a = out, path_out = out, overwrite_safe = FALSE
)
```
However I obtain the following error:

[2021-07-14 11:11:04] #### Starting sen2r execution. ####
[2021-07-14 11:11:04] Searching for available SAFE products...
[2021-07-14 11:11:18] Querying Google Cloud (this can take a very long time)...

**Error in as.Date.default(sensing_datetime) (downloader_solver2.r.R#53): do not know how to convert 'sensing_datetime' to class “Date”
Show stack trace**

How can I fix it or, how to incorporate my post-download processing steps with `s2_download()`?

Thank you,

Sergio.

_PD: @ranghetti , thank you very much for your great work and for implementing the download through Google Cloud. I reported over 50 invalid .SAFE products to Copernicus Technical Support but have received no response. I hope this problem will be fixed soon... Thank you very much for offering alternatives._

**Comment by ranghetti** [comment]
Thank you for your appreciation.
Very strange issue, which I am not able to reproduce (neither on Linux nor on Windows).
Try passing `timewindow = c("2019-06-01", "2019-06-30")` instead than `timewindow = time_window`, or explicitly load package {data.table} before running `sen2r(...)`.

**Comment by sermomon** [comment]
> Thank you for your appreciation.
> Very strange issue, which I am not able to reproduce (neither on Linux nor on Windows).
> Try passing `timewindow = c("2019-06-01", "2019-06-30")` instead than `timewindow = time_window`, or explicitly load package {data.table} before running `sen2r(...)`.

**Comment by sermomon** [comment]
> Thank you for your appreciation.
> Very strange issue, which I am not able to reproduce (neither on Linux nor on Windows).
> Try passing `timewindow = c("2019-06-01", "2019-06-30")` instead than `timewindow = time_window`, or explicitly load package {data.table} before running `sen2r(...)`.

Fixed using time window = c (date, date1). Thank you!

**Comment by liomarcus** [comment]
I still have some issues with the `sensing date` and the exact same error message. I tried to pass `time_interval = c("2021-03-01", "2021-10-31")`, but without success. Furthermore, I also explicitly loaded the package {data.table} before running `s2_list(...)`.

here the error again:
`old-style crs object detected; please recreate object with a recent sf::st_crs()
old-style crs object detected; please recreate object with a recent sf::st_crs()
[2022-01-13 16:59:44] Querying Google Cloud (this can take a very long time)...
Error in as.Date.default(sensing_datetime) : 
  do not know how to convert 'sensing_datetime' to class “Date”
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  running command 'C:\Users\marku\GOOGLE~1\GOOGLE~1\bin\gsutil ls gs://gcp-public-data-sentinel-2/tiles/32/S/MJ' had status 1
2: In FUN(X[[i]], ...) :
  running command 'C:\Users\marku\GOOGLE~1\GOOGLE~1\bin\gsutil ls gs://gcp-public-data-sentinel-2/L2/tiles/32/S/MJ' had status 1`

... and my session infos:

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_Austria.1252  LC_CTYPE=English_Austria.1252    LC_MONETARY=English_Austria.1252 LC_NUMERIC=C                    
[5] LC_TIME=English_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sen2r_1.5.0.9000  data.table_1.14.0 rLandsat_0.1.1    cgaR_0.0.0.9000   remotes_2.2.0     devtools_2.3.0    usethis_1.6.1     rvest_0.3.5      
 [9] xml2_1.3.2        imager_0.42.3     magrittr_2.0.1    snow_0.4-4        ClusterR_1.2.4    stringr_1.4.0     gtools_3.8.2      dplyr_0.8.5      
[17] sf_1.0-6          raster_3.4-10     sp_1.4-5         

loaded via a namespace (and not attached):
 [1] fs_1.4.1           doParallel_1.0.16  httr_1.4.2         rprojroot_1.3-2    tools_3.6.3        backports_1.1.6    rgdal_1.5-23      
 [8] utf8_1.2.1         R6_2.5.1           KernSmooth_2.23-16 rgeos_0.5-5        DBI_1.1.2          lazyeval_0.2.2     colorspace_1.4-1  
[15] withr_2.4.3        readbitmap_0.1.5   tidyselect_1.1.1   prettyunits_1.1.1  processx_3.4.2     curl_4.3.2         compiler_3.6.3    
[22] cli_2.5.0          geojsonsf_2.0.1    desc_1.2.0         scales_1.1.0       classInt_0.4-3     readr_1.4.0        callr_3.4.3       
[29] proxy_0.4-25       digest_0.6.25      tiff_0.1-5         foreign_0.8-75     jpeg_0.1-8.1       pkgconfig_2.0.3    sessioninfo_1.1.1 
[36] rlang_0.4.11       httpcode_0.3.0     jsonlite_1.7.2     Rcpp_1.0.6         munsell_0.5.0      fansi_0.4.2        abind_1.4-5       
[43] lifecycle_1.0.1    stringi_1.4.6      jqr_1.2.2          pkgbuild_1.0.7     maptools_1.1-1     grid_3.6.3         parallel_3.6.3    
[50] crayon_1.4.2       RcppTOML_0.1.7     geojsonio_0.9.4    lattice_0.20-38    stars_0.5-5        geojson_0.3.4      hms_1.1.1         
[57] ps_1.3.2           pillar_1.6.4       igraph_1.2.6       codetools_0.2-16   pkgload_1.0.2      crul_1.2.0         XML_3.99-0.3      
[64] glue_1.4.2         V8_4.0.0           bmp_0.3            png_0.1-7          vctrs_0.3.8        foreach_1.5.1      testthat_2.3.2    
[71] gtable_0.3.0       purrr_0.3.4        assertthat_0.2.1   ggplot2_3.3.0      lwgeom_0.2-6       e1071_1.7-6        class_7.3-15      
[78] tibble_3.1.1       iterators_1.0.13   memoise_1.1.0      units_0.7-1        gmp_0.6-2          ellipsis_0.3.2    
> packageVersion("sen2r")
[1] ‘1.5.0.9000’
```

Thank for your awesome tool and all your efforts in advance,
cheers,
Marcus

**Comment by ranghetti** [comment]
@liomarcus please post your `s2_list(...)` command (together with the preceeding code required to ensure code reproducibility).

**Comment by liomarcus** [comment]
Please find my simple query code below:

```
require(sen2r)

check_gcloud()
check_gcloud_connection()
is_gcloud_configured()

period2download = as.Date(c("2021-03-01", "2021-10-31"))

example_s2_list <- s2_list(
  spatial_extent = NULL,
  server = "gcloud",
  orbit = "122",
  tile = "33UVP",
  time_interval = period2download
)
```

The Output:

```
> require(sen2r)
Loading required package: sen2r
Registered S3 method overwritten by 'geojsonsf':
  method        from   
  print.geojson geojson
Welcome to sen2r. To use the package from a GUI, launch
 > sen2r()
Documentation: https://sen2r.ranghetti.info
Help and bug report: https://github.com/ranghetti/sen2r/issues
> 
> check_gcloud()
> check_gcloud_connection()
[1] TRUE
> is_gcloud_configured()
[1] TRUE
> 
> period2download = as.Date(c("2021-03-01", "2021-10-31"))
> 
> example_s2_list <- s2_list(
+   spatial_extent = NULL,
+   server = "gcloud",
+   orbit = "122",
+   tile = "33UVP",
+   time_interval = period2download
+ )
Spherical geometry (s2) switched off
old-style crs object detected; please recreate object with a recent sf::st_crs()
old-style crs object detected; please recreate object with a recent sf::st_crs()
[2022-01-15 12:01:16] Querying Google Cloud (this can take a very long time)...
Error in as.Date.default(sensing_datetime) : 
  do not know how to convert 'sensing_datetime' to class “Date”
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  running command 'C:\Users\marku\GOOGLE~1\GOOGLE~1\bin\gsutil ls gs://gcp-public-data-sentinel-2/tiles/33/U/VP' had status 1
2: In FUN(X[[i]], ...) :
  running command 'C:\Users\marku\GOOGLE~1\GOOGLE~1\bin\gsutil ls gs://gcp-public-data-sentinel-2/L2/tiles/33/U/VP' had status 1
Spherical geometry (s2) switched on
> 
```
